# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello_OmniSci": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://{user}.github.io/{lib_name}/"

git_url = "https://github.com/{user}/{lib_name}/tree/{branch}/"

def custom_doc_links(name): return None
