# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['hello_OmniSci']

# Cell
def hello_OmniSci():
    "Makes sure our OmniSci connection is available and working"
    return f'Hi there.  OmniSci connection not yet set!'
